Yunai39\Bundle\SimpleLdapBundle\Entity\RoleLdap:
    type: entity

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleName:
            type: string
            length: '255'
