Yunai39\Bundle\SimpleLdapBundle\Entity\UserLdap:
    type: mappedSuperclass
    fields:

        idLdap:
            type: string
            length: '255'
        valid:
            type: boolean
            nullable: true
    manyToMany:
        roles:
            targetEntity: RoleLdap
            cascade: ["persist", "merge"]