Yunai39\Bundle\SimpleLdapBundle\Entity\UserLdap:
    type: mappedSuperclass
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        idLdap:
            type: string
            length: '255'
        role:
            type: string
            length: '255'
        valid:
            type: boolean
            nullable: true
