parameters:
    security_ldap.class: Yunai39\Bundle\SimpleLdapBundle\Service\LdapService
    security_ldap_provider.class: Yunai39\Bundle\SimpleLdapBundle\Security\User\UserLdapProvider
    security_authentification_provider.class: Yunai39\Bundle\SimpleLdapBundle\Security\Authentification\LdapAuthProvider
    security_ldap_listener.class: Yunai39\Bundle\SimpleLdapBundle\Security\Listener\SecurityListener
    security.authentication.success_handler.class: Yunai39\Bundle\SimpleLdapBundle\Handler\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: Yunai39\Bundle\SimpleLdapBundle\Handler\AuthenticationFailureHandler
    security.user_ldap_repository.class: Yunai39\Bundle\SimpleLdapBundle\Entity\UserLdapRepository
    security.user_ldap.class: Yunai39\Bundle\SimpleLdapBundle\Entity\UserLdap


services:
  
    user_ldap_repository:
        class: "%security.user_ldap_repository.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "%security.user_ldap.class%"
    security_ldap_service:
        class: "%security_ldap.class%"
        arguments: ["%simple_ldap.settings%"]
    security_ldap_provider:
        class: "%security_ldap_provider.class%"
        arguments: ["%simple_ldap.settings_user%",%simple_ldap.default_role%,"%simple_ldap.user_class%",@user_ldap_repository]
    security_authentification_provider:
        class: "%security_authentification_provider.class%"
        arguments: ["@security_ldap_provider",  "@security_ldap_service"]


    security.authentication.success_handler:
        class:  "%security.authentication.success_handler.class%"
        arguments:  ["@security.http_utils", {},'@router', '%simple_ldap.user_redirects%']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    security.authentication.failure_handler:
        class:  "%security.authentication.failure_handler.class%"
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }