parameters:
    security_ldap.class: Yunai39\Bundle\SimpleLdapBundle\Service\LdapService
    security_ldap_provider.class: Yunai39\Bundle\SimpleLdapBundle\Security\User\UserLdapProvider
    security_authentification_provider.class: Yunai39\Bundle\SimpleLdapBundle\Security\Authentification\LdapAuthProvider
    security_ldap_listener.class: Yunai39\Bundle\SimpleLdapBundle\Security\Listener\SecurityListener
    security.authentication.success_handler.class: Yunai39\Bundle\SimpleLdapBundle\Handler\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: Yunai39\Bundle\SimpleLdapBundle\Handler\AuthenticationFailureHandler

services:
  
    security_ldap_service:
        class: "%security_ldap.class%"
        arguments: ["%ldap.settings%"]
    security_ldap_provider:
        class: "%security_ldap_provider.class%"
        arguments: ["%ldap.settings.user%",%ldap.settings.role%,"%ldap.user.class%","%ldap.role%"]
    security_authentification_provider:
        class: "%security_authentification_provider.class%"
        arguments: ["@security_ldap_provider",  "@security_ldap_service"]


    security.authentication.success_handler:
        class:  "%security.authentication.success_handler.class%"
        arguments:  ["@security.http_utils", {},'@router', '%ldap.security.redirects%']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    security.authentication.failure_handler:
        class:  "%security.authentication.failure_handler.class%"
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }